python train_mlm_flax.py \
    --output_dir="./output_dir_2_continue" \
    --validation_split_percentage 0.1 \
    --do_train \
    --do_eval \
    --per_device_train_batch_size="1024" \
    --per_device_eval_batch_size="1024" \
    --learning_rate="9e-4" \
    --num_train_epochs 20 \
    --warmup_steps="500" \
    --logging_steps="30" \
    --save_steps="500" \
    --eval_steps="5000" \
    --seed="42" \
    --model_name_or_path="/home/penguin/microlm/output_dir_2" \
    --tokenizer_name="./bpe-tokenizer-ka" \
    --dtype="float16" \
    --token="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" \
    --dataset_name="uonlp/CulturaX" \
    --dataset_config_name="ka" \
    --max_seq_length="32" \
    --preprocessing_num_workers="15" \
    --overwrite_cache true 